image: node:lts-alpine

options:
  max-time: 10

pipelines:
  branches:
    master:
      - step:
          name: Build and deploy library to NPM
          caches:
            - node
          script:
            - npm ci
            - npm run tsc
            - pipe: atlassian/npm-publish:0.2.1  
              variables:
                NPM_TOKEN: '$NPM_TOKEN'
                EXTRA_ARGS: '--access restricted'